layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options: stars
  limit: 10
  exclude:
    archived: false
    forks: true
    projects:
      - mrtkp9993.github.io
      - StochasticProcessExamplesR
      - StreamingDataShiny
      - SimpleCRUDAppNetCore
      - bayesciistatistik

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: muratkoptur
  # mastodon: your_username
  medium: muratkoptur
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://makineogrenimi.wordpress.com
  # youtube: your_username

topics:
  - name: R
    image_url: https://cran.r-project.org/Rlogo.svg
  - name: C++
    image_url: https://isocpp.org/files/img/cpp_logo.png
  - name: Haskell
    image_url: https://www.haskell.org/img/haskell-logo.svg
  - name: Statistics & Data Science
  - name: Genomics